### ISSUE TITLE
Definir Requisitos Funcionales y Requisitos no Funcionales

### ISSUE THREAD

**Issue by AdrianBueno** [Arquisoft/Trivial1b#3]
Hay que definir exactamente los requisitos funcionales y no funcionales, en la wiki mismamente, previa  a la creación de la documentación final.

**Comment by mariahernantinez** [comment]
Acabo de subir la primera versión de los requisitos, (he intentado editar el milestone y creo que me lo he cargado un poco, estoy intentando arreglarlo)

**Comment by mariahernantinez** [comment]
Vale me ha cerrado el milestone cuanto queria darle para atrás, si no hay que cerrarlo aun creo otro cuando comenteis

**Comment by samuelfdezc** [comment]
Acabo de leer lo que pusiste y he añadido un requisito no funcional que se comento el otro día en clase. El resto creo que están bien. Si se le ocurre alguna más a alguien, que las ponga.

**Comment by AdrianBueno** [comment]
Por favor, duplicad vuestros cambios en .docx en documentación, si no, no contarán como commits....

Puesto que ya está hecho, cierro este Issue..
