### ISSUE TITLE
Escenarios de calidad

### ISSUE THREAD

**Issue by AdrianBueno** [Arquisoft/Trivial1b#4]
He subido un .docx con mi idea de los escenarios de calidad, los escenarios de calidad en la wiki, están más o menos bien, de no ser por ciertas mediciones de respuesta y la falta del atributo afectado, recomiendo mezclarlo y revisar después.

**Comment by MariSanz** [comment]
Vale, ya he visto el doc, esta más comprimida la información, y españolizado el nombre del artefacto afectado como extractor de preguntas o procesador de peguntas; no había puesto los atributos de calidad afectados porque aun no estaban hechos por la otra compañera, ya lo adaptaré, de todas maneras decir ya consulte al profesor sobre como había yo redactado los  escenarios de calidad.

**Comment by AdrianBueno** [comment]
Si mira a ver si puedes refinarlo, porque por ejemplo, las mediciones de respuesta, me he guidado por ejemplos, pero no tengo claro que pueda poner un "Tiempo de respuesta y un %" así sin más...
Y si encuentras más escenarios para cada atributo ya queda perfecto.
En cuánto a los nombres de artefacto, pues no se que usar, aún tengo esta duda mientras espero por el diagrama de paquetes.. y aún así..
Estaba pensando en llamar al sistema completo "Procesador de preguntas" y "Extractor" y "Almacenador" puedes ponerlos en inglés.... Sin embargo quizás haya nombres más adecuados.... Pero aquí no hay interfaz propiamente dicha, solo es un motor, un backend.. asique no puedo denominar backend y frontend  así por las buenas.... Si tienes duda de alguno.. consultalo a un profesor mejor.

**Comment by AdrianBueno** [comment]
He actualizado el <a href="https://github.com/Arquisoft/Trivial1b/blob/master/Documentacion/Escenarios%20de%20calidad.docx">Escenarios de calidad.docx</a> otra vez, cambiado el origen de los 2 primeros escenarios, creo que se puede medir sus respuestas en tiempo efectivo. 
Si puedes compararlo con el de la wiki, si hace falta algún escenario más o modificar alguno, comentalo poraquí y después actualizalo.

**Comment by MariSanz** [comment]
Vale, te dije los terminaba una vez me conteste el profesor, lunes 23 de tarde subo versión definitiva que haga yo.

**Comment by AdrianBueno** [comment]
Al final los he actualizado y mejorado, versión definitiva de la práctica 1 hecha.
