### ISSUE TITLE
Ajustar wiki a la documentación.

### ISSUE THREAD

**Issue by AdrianBueno** [Arquisoft/Trivial1b#7]
La wiki está desactualizada, los documentos .docx tienen la documentación más refinada, hay que actualizar la wiki a partir de los mismos...

**Comment by MariSanz** [comment]
He subido un doc con el formato de la documentación, seria donde recoger todas las partes; revisad si os parece y seria este el que habría de ir actualizando cuando fuere necesario.

**Comment by AdrianBueno** [comment]
Pero entonces ahora cada vez que haga un cambio en los .docx, que serán bastantes, tendrás que cambiarlo ahí también...

**Comment by MariSanz** [comment]
Vale, sin problema, 1 o 2 días antes de la entrega lo actualizo, para que este correcto; hay que revisar el formato si os parece bien, para eso lo subi antes.

**Comment by AdrianBueno** [comment]
Vamos a ver, pero esto <a href="https://github.com/Arquisoft/Trivial1b/wiki/Escenarios-de-calidad"> Escenarios de calidad</a> ¿Por qué se ha puesto así? Eso son los atributos, no los escenarios.
<a href="https://github.com/Arquisoft/Trivial1b/wiki/Atributos-de-calidad-e-interesados">Atributos de calidad e interesados</a> Esto no tiene si quiera nada. Y ya va para 20 dias, y tenía que estar actualizado hace 2 semanas.

**Comment by mariahernantinez** [comment]
He añadido las tablas correspondientes a los dos apartados mencionados

**Comment by AdrianBueno** [comment]
Muchas gracias María.
